/** Public URLs (PRD §7). Latin slug + numeric id where the id is canonical. */
export const routes = {
  home: '/',
  people: '/people',
  parliament: '/parliament',
  cabinet: '/cabinet',
  search: '/search',
  corrections: '/corrections',
  reply: '/reply',
  contact: '/contact',
  about: '/about',
  editorialPolicy: '/about/editorial-policy',
  methodology: '/about/methodology',
  ownership: '/about/ownership',
  privacy: '/about/privacy',
  terms: '/about/terms',
  article: (article: { id: number; slug: string }) => `/news/${article.id}-${article.slug}`,
  /** Generated 1200×630 share card for an article without a cover (app/news/[idSlug]/share-card). */
  articleShareCard: (article: { id: number; slug: string }) => `/news/${article.id}-${article.slug}/share-card`,
  person: (person: { id: number; slug: string }) => `/person/${person.id}-${person.slug}`,
  party: (slug: string) => `/party/${slug}`,
  tag: (slug: string) => `/tag/${slug}`,
  /** A section (category) listing; page 1 has no number (PRD §7), later pages are `/section/{slug}/{n}`. */
  section: (slug: string, page = 1) => (page > 1 ? `/section/${slug}/${page}` : `/section/${slug}`),
  /** Generated 1200×630 share card for a section (app/section/[slug]/share-card). */
  sectionShareCard: (slug: string) => `/section/${slug}/share-card`,
} as const;

/** Latin slug as generated by @news/shared/translit: lowercase words joined by single dashes. */
const SLUG = '[a-z0-9]+(?:-[a-z0-9]+)*';
const ID_SLUG_RE = new RegExp(`^(\\d{1,15})-(${SLUG})$`);
const SLUG_RE = new RegExp(`^${SLUG}$`);

/** `42-ikh-khural-tosov` → `{ id: 42, slug: 'ikh-khural-tosov' }`; null if the segment is not `{id}-{slug}`. */
export function parseIdSlug(segment: string): { id: number; slug: string } | null {
  const match = ID_SLUG_RE.exec(segment);
  if (!match) return null;
  const id = Number(match[1]);
  return id > 0 ? { id, slug: match[2]! } : null;
}

/** The segment if it is a valid slug, else null (so junk URLs 404 without an API request). */
export function parseSlug(segment: string): string | null {
  return segment.length <= 200 && SLUG_RE.test(segment) ? segment : null;
}

/** Highest page number a listing URL accepts; anything above is treated as not found. */
const MAX_PAGE = 10_000;

/** `/section/{slug}/{n}` page number: digits without a leading zero, 1–10 000; else null. */
export function parsePage(segment: string): number | null {
  if (!/^[1-9]\d{0,4}$/.test(segment)) return null;
  const page = Number(segment);
  return page <= MAX_PAGE ? page : null;
}
